# Read the Docs configuration file for Financial Debt Optimizer
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate API documentation
      - sphinx-apidoc -f -o docs/api src --separate --module-first --implicit-namespaces
      # Generate test reports  
      - python scripts/generate_test_reports.py || echo "Test report generation failed, continuing..."
    
# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .

# Exclude certain patterns when building documentation
# We exclude the build directories, version control, and unnecessary files
submodules:
  exclude:
    - all