# Financial Debt Optimizer Configuration File
# This file contains default settings for the debt optimizer tool.
# Default location: ~/.debt-optimizer
# Alternative: ./debt-optimizer.yaml in your project directory

# File Paths
# ----------
# Path to input Excel file with debt/income data
input_file: default.xlsx

# Path to output Excel file for analysis results
output_file: debt_analysis.xlsx

# Path to Quicken SQLite database for balance updates
# Example: ~/Documents/YourName.quicken/data
# Adjust this to match your Quicken data location
quicken_db_path: ~/Documents/Quicken.quicken/data

# Analysis Settings
# -----------------
# Optimization goal: minimize_interest, minimize_time, or maximize_cashflow
optimization_goal: minimize_interest

# Extra monthly payment to apply towards debts (dollars)
extra_payment: 0.0

# Emergency fund amount to maintain (dollars)
emergency_fund: 1000.0

# Balance Update Settings  
# -----------------------
# Minimum fuzzy match score (0-100) for account name matching
fuzzy_match_threshold: 80

# Name of checking account to use for current bank balance in Settings sheet
# Example: "My Checking Account" or "Primary Checking"
bank_account_name: Primary Checking

# Automatically create timestamped backup before updating balances
auto_backup: true

# Output Settings
# ---------------
# Generate simplified one-sheet summary report
simple_report: false

# Compare all available strategies in the report
compare_strategies: false
